name: Generate The Commits Snake

on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:

jobs:
  generate-snake:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: Platane/snk@master
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            github-snake.svg
            github-snake-dark.svg?palette=github-dark
            github-test.svg?color_snake=orange&color_dots=#bfd6f6,#8dbdff,#64a1f4,#4b91f1,#3c7dd9
      - uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: master
          build_dir: /
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
